vscode:
  extensions:
    - msjsdiag.debugger-for-chrome@4.12.0:7EFH+WbhN0WseuD5ON5hRQ==
    - karigari.chat@0.22.1:nC6st9eBKbWtnQ6UFuqnXg==
    - cweijan.vscode-mysql-manager@1.5.2:1OopbkeRurZqjn6By0D2bA==
    - danwahlin.angular2-snippets@1.0.21:BiIkxnWM/hp58sHLSZDe/Q==
    - eamodio.gitlens@10.0.1:JFmNfkpc+L/v1Y3k+7HxhA==
    - johnpapa.Angular2@8.1.1:5n047Q4w8oMstLXJadb7tg==
    - pmneo.tsimporter@2.0.1:LI0jZxdaZNXYOYbOWaaIvA==